/*
 * Tag → Material Symbols icon mapping.
 * Falls back to 'label' for anything not listed here.
 */

export const TAG_ICONS = {
  '2FA': 'passkey',
  'Ad Blocker': 'block',
  'App Manager': 'apps',
  'App Store': 'store',
  'Artificial Intelligence': 'smart_toy',
  'Backup': 'backup',
  'Battery': 'battery_full',
  'Browser': 'language',
  'Bookmark Manager/Read It Later': 'bookmark',
  'Chromium Based': 'language',
  'Gecko Based (Firefox)': 'language',
  'Calculator': 'calculate',
  'Calendar': 'calendar_month',
  'Camera': 'photo_camera',
  'Chat & Messaging': 'chat',
  'Matrix': 'chat',
  'Signal': 'chat',
  'Telegram': 'send',
  'Clock & Time': 'schedule',
  'Timer': 'timer',
  'Communication': 'call',
  'Contact': 'contacts',
  'Call Blocker/Spam Filter': 'phone_disabled',
  'Dialer': 'dialpad',
  'SMS': 'sms',
  'Device automation': 'memory',
  'Diary & Journal': 'edit_note',
  'Dictionary': 'menu_book',
  'Downloader & Manager': 'download',
  'Drawing': 'draw',
  'Email': 'mail',
  'Email Alias': 'alternate_email',
  'Email Client': 'mail',
  'Email Forwarding': 'forward_to_inbox',
  'File': 'folder',
  'File Manager': 'folder_open',
  'File Sharing': 'share',
  'Finance': 'payments',
  'Card Wallet': 'account_balance_wallet',
  'Expense Tracker': 'receipt_long',
  'Flashcard': 'quiz',
  'Flashlight': 'flashlight_on',
  'Games & Emulator': 'sports_esports',
  'Board': 'chess',
  'Card': 'playing_cards',
  'Educational': 'school',
  'Emulators': 'videogame_asset',
  'Logic': 'extension',
  'Puzzle': 'extension',
  'Snake': 'sports_esports',
  'Sudoku': 'grid_on',
  'Tic Tac Toe': 'tag',
  'Quiz/Trivia': 'quiz',
  'Online': 'cloud',
  'Icon Pack': 'palette',
  'Image': 'image',
  'Image Manipulation': 'tune',
  'Image Viewer & Gallery': 'photo_library',
  'Keyboard': 'keyboard',
  'Launcher': 'home',
  'Maps & Navigation': 'map',
  'Media (Audio/Video)': 'play_circle',
  'Equalizer': 'equalizer',
  'Music': 'music_note',
  'Music/Audio Player': 'headphones',
  'Podcast/Audio Player': 'podcasts',
  'Subsonic Client': 'library_music',
  'Spotify Client': 'library_music',
  'Streaming': 'live_tv',
  'YouTube': 'smart_display',
  'YouTube Music': 'library_music',
  'Twitch': 'live_tv',
  'Video Player': 'movie',
  'Video Editor': 'movie_edit',
  'Network': 'wifi',
  'DNS': 'dns',
  'Firewall': 'security',
  'Link': 'link',
  'Note': 'note',
  'Office': 'description',
  'Optimizer & Cleaner': 'cleaning_services',
  'Painting': 'palette',
  'Password & Authentication': 'lock',
  'Privacy': 'shield',
  'File & App Encryption': 'enhanced_encryption',
  'Permission Manager': 'admin_panel_settings',
  'Recorder': 'mic',
  'Reader & Viewer': 'auto_stories',
  'PDF': 'picture_as_pdf',
  'Manga & Anime': 'auto_stories',
  'News': 'newspaper',
  'RSS Reader': 'rss_feed',
  'Research & Development': 'science',
  'Sandboxing': 'security',
  'Science & Education': 'biotech',
  'Scanner': 'qr_code_scanner',
  'QR & Barcode Scanner': 'qr_code_scanner',
  'Document Scanner': 'document_scanner',
  'Shopping': 'shopping_cart',
  'Social Network': 'group',
  'Discord': 'forum',
  'Facebook': 'group',
  'Github': 'code',
  'Lemmy': 'forum',
  'Mastodon': 'forum',
  'Pixiv': 'brush',
  'Reddit': 'forum',
  'Steam': 'sports_esports',
  'VK': 'group',
  'X(Twitter)': 'forum',
  'Xda': 'forum',
  'Sport & Health': 'fitness_center',
  'Tracker': 'monitoring',
  'Synchronisation': 'sync',
  'System': 'settings',
  'ADB Tools': 'terminal',
  'Gesture Control': 'swipe',
  'GSI': 'developer_board',
  'Info': 'info',
  'Phone Link': 'devices',
  'Shizuku': 'developer_mode',
  'SuperUser': 'admin_panel_settings',
  'Terminal': 'terminal',
  'Theme': 'dark_mode',
  'Text Editor & Code Editor/IDE': 'code',
  'Text-to-Speech': 'record_voice_over',
  'ToDo List': 'checklist',
  'Translator': 'translate',
  'URL Manipulation': 'link',
  'Utilities': 'build',
  'VM': 'developer_board',
  'VPN': 'vpn_lock',
  'Wallpaper': 'wallpaper',
  'Weather': 'wb_sunny',
  'IDK': 'help',
  'Other': 'more_horiz',
  'Tools': 'build',
  'Book/Ebook': 'auto_stories',
  'Torrent': 'download',
  'Video': 'videocam',
};

export function iconFor(tag) {
  return TAG_ICONS[tag] ?? 'label';
}
